# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/College/Thesis/VivadoProjects/my_bram/my_bram.cache/wt [current_project]
set_property parent.project_path C:/College/Thesis/VivadoProjects/my_bram/my_bram.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4:part0:1.1 [current_project]
set_property ip_output_repo c:/College/Thesis/VivadoProjects/my_bram/my_bram.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/College/Thesis/VivadoProjects/my_bram/my_bram.srcs/sources_1/new/my_bram.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top my_bram -part xc7a100tcsg324-1


write_checkpoint -force -noxdef my_bram.dcp

catch { report_utilization -file my_bram_utilization_synth.rpt -pb my_bram_utilization_synth.pb }
